Upjuyanolja/Upjuyanolja_FE

craco.config.js
package.json
src/layout.tsx

craco로 인해 antd 적용이 안됐고 이 부분 해결했습니다
추가로 layout 수정했습니다

Fix: antd 적용 문제 해결

---

.babelrc
src/test/layouts/footer/footer.test.tsx
src/test/layouts/footer/index.tsx

close #15 
jsx오류 해결을 위한 .babelrc 파일 생성 하였습니다.
test폴더 내 index.tsx는 테스트를 위해 스타일링은 전혀 하지 않고 기능 확인을 위한 파일입니다. 
비즈니스 로직 작성 시 요구 사항대로 스타일링 할 예정입니다.
저희 테스트 폴더가 __test__가 아니므로 컴포넌트명.test.ts or 컴포넌트명.test.tsx로 해주셔야 합니다.
테스트 진행 시 'npx jest 해당하는 테스트 파일의 컴포넌트 명'을 명령어로 하시면 됩니다. 저의 경우 npx jest footer 입니다!
그리고 테스트 진행 시 저와 비슷하게 외부 url 이동 테스트를 할 땐 테스트 코드 최상단에
```
/**
* @jest-environment jsdom
*/
```
이거 해주셔야 합니다. 
왜냐하면 jest는 node 환경인데 window 객체를 가져오기 위해서는 jsdom 환경을 만들어 주어야 합니다. 
node 환경에서는 window.location.href 등 과 같은 프로퍼티는 접근이 불가능 하다고 합니다! 
따라서 jsdom을 사용하여 가상으로 접근하여 테스트 하는 방식을 사용해야 합니다!
https://somedaycode.tistory.com/17

Test: 로그인 / 회원 가입 공통 푸터 테스트 코드

---

src/components/coupon-registration/coupon-preview/coupoin-preview-item/index.tsx
src/components/coupon-registration/coupon-preview/coupoin-preview-item/type.ts
src/components/coupon-registration/coupon-preview/index.tsx
src/components/spacing/index.tsx
src/components/spacing/type.ts
src/pages/coupon-registration/index.tsx

Style: 쿠폰 미리보기 컴포넌트 퍼블리싱

---

src/components/modal/payment/cancel/index.tsx
src/components/modal/payment/common/company-info/index.tsx
src/components/modal/payment/common/coupon-info/index.tsx
src/components/modal/payment/common/order-info/index.tsx
src/components/modal/payment/common/order-point-info/index.tsx
src/components/modal/payment/common/order-point-info/types.tsx
src/components/modal/payment/receipt/index.tsx
src/pages/point-detail/index.tsx

Style: 결제 영수증, 취소 요청 모달 퍼블리싱

---

src/api/room/type.ts
src/components/init/ButtonContainer.tsx
src/components/init/CheckBoxContainer.tsx
src/components/init/ImageUploadContainer.tsx
src/components/init/init-accommodation-registration/type.ts
src/components/init/init-info-confirmation/RoomItem.tsx
src/components/init/type.ts
src/components/room/capacity-container/index.tsx
src/components/room/num-of-rooms-container/index.tsx
src/components/room/price-container/index.tsx
src/components/room/time-container/index.tsx
src/components/room/time-container/type.ts
src/pages/init-accommodation-registration/index.tsx
src/pages/init-info-confirmation/index.tsx
src/pages/init-room-registration/index.tsx
src/stores/init/atoms.ts
src/stores/init/type.ts

Feat: 등록 정보 확인하기 페이지 - 객실, 숙소 수정

---

src/api/coupon/index.ts
src/assets/data/couponData.json
src/assets/data/revenueData.json
src/assets/data/staticsData.json
src/components/coupon/additional-purchase-footer/index.tsx
src/components/coupon/additional-purchase-footer/type.ts
src/hooks/coupon/useCoupon.ts
src/hooks/main/useMain.ts
src/mocks/accommodation/index.ts
src/mocks/coupon/index.ts
src/mocks/handlers.ts
src/pages/coupon/index.tsx
src/queries/coupon/index.ts

**보유 숙소 목록 조회, 포인트 요약조회, 쿠폰 관리쪽 api, 메인 페이지 api는
msw랑 통신하도록 수정했습니다!
이유는 아직 서버 구현이 제대로 안되었기 때문입니당
담당자분들 참고해주세요!**

Fix: 쿠폰 도메인 api response 형태 수정 

---

src/api/index.tsx
src/components/layout/side-bar/signout-btn/index.tsx
src/pages/sign-in/index.tsx
src/utils/sign-up/ValidateSchema.ts

close #200 
대문자 1개 이상, 소문자 1개 이상, 숫자 1개 이상 이면서 8글자에서 20글자 사이로 유효성 검사 수정했습니다~
그리고 로그인 시 숙소 목록 조회해 숙소가 있는 경우 쿠키에 제일 작은 accommodationId를 넣고 /${accommodationId}/main 으로 가게 했습니다.
없는 경우 /init으로 가게 했습니다.

Fix: 회원 가입 비밀 번호 유효성 검사 로직 수정

---

src/pages/sign-in/index.tsx

close #213 
pm님의 요청으로 52px인 gap을 32px로 변경하였습니다.

Style: 로그인 화면 퍼블리싱 수정

---

src/api/init/index.ts
src/components/init/init-accommodation-registration/RadioButtonCustomContainer.tsx
src/components/init/init-info-confirmation/AccommodationInfo.tsx
src/components/init/init-info-confirmation/CustomButton.tsx
src/components/init/init-info-confirmation/RoomItem.tsx
src/components/layout/init-layout/InitLayout.tsx
src/mocks/handlers.ts
src/pages/init-accommodation-registration/index.tsx
src/pages/init-info-confirmation/index.tsx
src/pages/init-room-registration/index.tsx

- 객실 수정 toast가 객실 추가 시에도 떠서 그를 방지하는 코드를 추가했습니다. 
- 플로우 담당 pm님의 요청으로 위,아래 헤더중 아래 헤더는 fixed를 해제했습니당
- 디자이너팀 스타일 수정 요청에 따라 스타일도 약간 수정했습니다
- 백엔드 서버 uri가 바뀌어서 수정했습니다

Fix: 숙소 등록 플로우 버그 수정

---

src/api/accommodation/index.ts
src/api/room/index.ts
src/api/room/type.ts
src/components/init/ImageUploadContainer.tsx
src/components/room/status-container/index.tsx
src/pages/room-management/index.tsx
src/pages/room-registration/index.tsx
src/pages/room-update/index.tsx
src/queries/room/index.ts
src/stores/init/type.ts
src/stores/room/atoms.ts
src/stores/room/type.ts

Feat: 객실 수정 api 연동 

---

src/pages/sign-in/index.tsx
src/pages/sign-up/index.tsx

close #219 
pm 분의 요구 사항에 맞춰 수정했습니다~

Fix: 로그인 퍼블리싱 및 회원 가입 border 수정

---

src/utils/sign-up/ValidateSchema.ts

close #225 
특수 문자 입력 못하게 바꿨습니다~

Fix: 특수 문자 제외 정규식 수정

---

src/api/point/index.ts

Chore: api 주소 변경사항 적용

---

src/api/room/index.ts
src/components/room/room-card/index.tsx

- 바뀐 api 주소 수정하고 디자인 수정 요청대로 작업했습니다~

Fix: API URI 및 스타일 수정

---

src/api/coupon/index.ts
src/api/coupon/type.ts
src/api/room/index.ts
src/components/coupon/coupon-header/index.tsx
src/components/coupon/coupon-status-tag/index.tsx
src/components/coupon/table/index.tsx
src/components/main/main-chart/index.tsx
src/components/main/main-coupon-status-container/index.tsx
src/components/main/main-coupon-status-container/type.ts
src/hooks/main/useMain.ts
src/index.css
src/pages/main/index.tsx
src/queries/coupon/index.ts
src/utils/dateFormat/dateFormat.ts

Feat: 쿠폰 통계 api 연결 

---

src/components/error/ServerError.tsx
src/components/room/status-container/index.tsx
src/pages/room-management/index.tsx
src/pages/room-registration/index.tsx
src/pages/room-update/index.tsx
src/pages/sign-in/index.tsx
src/pages/sign-up/index.tsx
src/queries/sign-in/index.ts
src/test/sign-up/SignUp.test.tsx
src/test/sign-up/index.tsx
src/utils/sign-up/ValidateSchema.ts

Fix: 객실 refetch 및 toggle error 해결 

---

src/components/layout/side-bar/accommodation-list/index.tsx
src/components/layout/side-bar/user-profile/index.tsx

Style: antd-btn 기본 border 삭제

---

src/components/main/main-coupon-status-container/index.tsx

Chore: 띄어쓰기 수정

---

src/components/room/price-container/index.tsx
src/pages/room-management/index.tsx

Fix: 디자인 및 객실 가격 수정

---

src/App.tsx
src/components/room/price-container/index.tsx
src/pages/room-management/index.tsx
src/pages/room-registration/index.tsx
src/pages/room-update/index.tsx

Fix: rafc 형식으로 수정

---

src/pages/sign-in/index.tsx

close #238 
쿠키에 남아 있는 accommodationId로 인해 버그가 생긴 다는 이슈를 전달 받아 수정했습니다~

Fix: 기존 accommodationId 삭제

---

src/hooks/main/useMain.ts

Chore: 쿠폰 메세지 더미데이터로 수정

---

src/components/layout/side-bar/accommodation-list/index.tsx

Style: 버튼 border 삭제
